@startuml
left to right direction

actor "Funcionario/\nAdministrador" as Funcionario
actor "Espectador" as Espectador

rectangle "Sistema Rede de Cinemas" {
  usecase "Manter cinemas" as UC1
  usecase "Manter filmes" as UC2
  usecase "Organizar sessoes" as UC3
  usecase "Registrar publico\nda sessao" as UC4
  usecase "Consultar totalizacoes" as UC5
  usecase "Consultar filmes\ne sessoes" as UC6
}

Funcionario --> UC1
Funcionario --> UC2
Funcionario --> UC3
Funcionario --> UC4
Funcionario --> UC5
Funcionario --> UC6
Espectador --> UC6
@enduml
